[project]
name = "rag-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jesse", email = "jbowlingxc@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "rank-bm25>=0.2.2",
]

[build-system]
requires = ["uv_build>=0.11.13,<0.12.0"]
build-backend = "uv_build"
